# Generated by Django 5.2.8 on 2025-11-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.IntegerField()),
                ('absolute_humidity', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('vapor_pressure_deficit', models.FloatField()),
            ],
        ),
    ]
